server:
  port: 9220

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders:
              - Authorization
              - Content-Type
      routes:
        - id: mpatients
          uri: ${MPATIENTS_URI:http://localhost:8081}
          predicates:
            - Path=/patient/*
        - id: mhistory
          uri: ${MHISTORY_URI:http://localhost:8082}
          predicates:
            - Path=/history/*
        - id: massessment
          uri: ${MASSESSMENT_URI:http://localhost:8083}
          predicates:
            - Path=/assessment/*

